# Generated by Django 5.0.3 on 2024-04-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom_user',
            managers=[
            ],
        ),
    ]
