# Generated by Django 5.0.3 on 2024-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_custom_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
