# Generated by Django 5.0.3 on 2024-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_custom_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='add_line1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='add_line2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='blood_group',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='landmark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
