# Generated by Django 5.0.3 on 2024-04-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_custom_user_add_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='last_name',
        ),
    ]
