# Generated by Django 5.0.3 on 2024-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_custom_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
