# Generated by Django 5.0.3 on 2024-04-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_email_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_tokens',
            name='created_at',
        ),
    ]
