# Generated by Django 5.0.3 on 2024-04-29 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_email_tokens_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_tokens',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
