# Generated by Django 5.0.3 on 2024-04-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_email_tokens_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('specialist', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mob_number', models.IntegerField(null=True)),
                ('clinic_number', models.IntegerField(null=True)),
                ('add_line1', models.CharField(max_length=100, null=True)),
                ('add_line2', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('hospital_name', models.CharField(max_length=200, null=True)),
                ('hospital_address', models.CharField(max_length=200)),
                ('hospital_state', models.CharField(max_length=50, null=True)),
                ('hospital_pincode', models.IntegerField(null=True)),
                ('fees', models.IntegerField(null=True)),
                ('days_avialable', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=300)),
                ('reg_number', models.CharField(max_length=20)),
                ('degree', models.FileField(upload_to='')),
                ('profile_picture', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=50)),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
