# Generated by Django 5.0.3 on 2024-04-29 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctor_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_profile',
            old_name='add_line1',
            new_name='add_line_1',
        ),
        migrations.RenameField(
            model_name='doctor_profile',
            old_name='add_line2',
            new_name='add_line_2',
        ),
        migrations.RemoveField(
            model_name='doctor_profile',
            name='nationality',
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='degree_upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='degree',
            field=models.CharField(max_length=50),
        ),
    ]
