# Generated by Django 5.0.3 on 2024-04-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_days_avialable_doctor_profile_days_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='degree_upload',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Degree/'),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='profile_picture',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Profile/'),
        ),
    ]
