# Generated by Django 5.0.3 on 2024-04-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_doctor_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
