# Generated by Django 5.0.3 on 2024-05-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
