# Generated by Django 5.0.3 on 2024-05-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_staff_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='degree_upload',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Media/Degree/'),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='profile_picture',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Media/Profile/'),
        ),
    ]
