# Generated by Django 5.0.3 on 2024-05-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='Experience',
            field=models.IntegerField(null=True),
        ),
    ]
