# Generated by Django 5.0.3 on 2024-05-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_doctor_profile_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_profile',
            old_name='Experience',
            new_name='experience',
        ),
    ]
