# Generated by Django 5.0.3 on 2024-05-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='experience',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
