# Generated by Django 5.0.3 on 2024-05-06 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_doctor_profile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='user',
        ),
        migrations.AddField(
            model_name='appointments',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
