# Generated by Django 5.0.3 on 2024-05-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_appointments_user_appointments_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='alternate_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appointments',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointments',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
