# Generated by Django 5.0.3 on 2024-05-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_appointments_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='degree_upload',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Media/Media/Degree/'),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='profile_picture',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Media/Media/Profile/'),
        ),
    ]
